defmodule InnWeb.SessionControllerTest do
  use InnWeb.ConnCase

  # @admin_jwt "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJpbm4iLCJleHAiOjE2MDM3MDUxMTcsImlhdCI6MTYwMTI4NTkxNywiaXNzIjoiaW5uIiwianRpIjoiNDVlOGI5Y2EtYWIxNy00MjM1LWJkYTEtZmQ1NzY4NWJmMzc0IiwibmJmIjoxNjAxMjg1OTE2LCJzdWIiOiIxIiwidHlwIjoiYWNjZXNzIn0.gD-QDIRmZA1l4yzJAgF1uUbcdeV3jFEuesx51oNzPKDpfSWolyAscsZxzihb4TD2wnrsXRizv7_W6kvLqnv9Ww"
  # @operator_jwt "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJpbm4iLCJleHAiOjE2MDM3MDUxNTcsImlhdCI6MTYwMTI4NTk1NywiaXNzIjoiaW5uIiwianRpIjoiYTY1NGZiMjgtODk2YS00ZmVhLThmMTctMjVmNzBlYjY0YmU0IiwibmJmIjoxNjAxMjg1OTU2LCJzdWIiOiIyIiwidHlwIjoiYWNjZXNzIn0.o6avnvJLdMboK7Bym3WnV5yqxCMXO8vGduZdhVrxyKjgetnAMG40p0TvxubjAWDlVlYoqUpBqd2vH04q5Dz75g"
  # @guest_jwt "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJpbm4iLCJleHAiOjE2MDM3MDUyMDgsImlhdCI6MTYwMTI4NjAwOCwiaXNzIjoiaW5uIiwianRpIjoiOTM0NjdjMzAtNGQ2MC00NmQ0LWFhMjQtMjk1M2IxYTdiYzY2IiwibmJmIjoxNjAxMjg2MDA3LCJzdWIiOiIzIiwidHlwIjoiYWNjZXNzIn0.fX7IgKrdgvOraFK-4TqzIMagomgFk5DrbYu6aKm7cG3xVkU3PPuNw2WEDi3pCv-10AfRKB8I64TDfd4doV5ncA"


  describe "index" do
    test "GET /sessions/new", %{conn: conn} do
      conn = get(conn, "/sessions/new")
      assert html_response(conn, 200) =~ "Авторизация"
    end
  end
end
